### ISSUE TITLE
Login to VK is not working

### ISSUE THREAD

**Issue by AntonSamokat** [enscogitans/vk-tg-chat-transferring#1]
Указал VK app ID в файле с параметрами env

При попытке выполнить:

python main.py login vk

Появляется ошибка:

Traceback (most recent call last):
  File "/media/sunkrop/data_system/sunkrop/development/code/python/vk-tg-chat-transferring/main.py", line 71, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/media/sunkrop/data_system/sunkrop/development/code/python/vk-tg-chat-transferring/main.py", line 61, in main
    vk_client = VkClient(config.vk)
  File "/media/sunkrop/data_system/sunkrop/development/code/python/vk-tg-chat-transferring/common/vk_client.py", line 40, in __init__
    raise ValueError(f"Failed to load token from {self.name}.session file. Did you login before?")
ValueError: Failed to load token from vk.session file. Did you login before?

**Comment by AntonSamokat** [comment]
To work around this problem need to create "vk.session" config file with the following dummy json content:
{"token": "123"}

After the first success run token in this config file will be updated on actual.

**Comment by enscogitans** [comment]
Спасибо за обратную связь
PR https://github.com/enscogitans/vk-tg-chat-transferring/pull/2 должен починить проблему

**Comment by AntonSamokat** [comment]
Благодарю, фикс работает
